name: .NET Framework CI
#für alle Push und pull-request auf dem Branch main.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#Die Aufgaben 
jobs:
  build:
    runs-on: windows-latest

    steps:
    # Check out the repository
    - uses: actions/checkout@v4

    # Set up MSBuild
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    # Restore dependencies
    - name: Restore dependencies
      run: nuget restore # DATEIN.sln --> # Hier beim DATEI.sln sollte den Pfad zum .sln Datei

    # Build and Test
    - name: Build and Test
      run: msbuild #DATEI.sln /p:Configuration=Release /p:RunCodeAnalysis=true --> # Hier beim DATEI.sln sollte den Pfad zum .sln Datei 
